#数据端口配置
server:
  port: 8085
  hostname: localhost
  ipAddress: 127.0.0.1
#默认使用配置
spring:
  profiles:
    active: dev
#数据源配置
datasource:
  url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
  username: zx
  password: 1
  driver-class-name: oracle.jdbc.OracleDriver
  # 使用druid数据源
  type: com.alibaba.druid.pool.DruidDataSource

#数据源配置
#公共配置与profiles选择无关 mapperLocations指的路径是src/DemoApplication/resources
#mybatis:
#typeAliasesPackage: com.szkingdom.qc.vo
#mapperLocations: classpath:mapper/*.xml